<<<<<<< HEAD
"""
Django settings for AwsNotifier project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
=======
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c
import os
from urllib2 import urlopen

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
<<<<<<< HEAD
#AWS_PUBLIC_IP = urlopen('http://instance-data/latest/meta-data/public-ipv4').read()
AWS_PUBLIC_IP = 'localhost'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/
=======
AWS_PUBLIC_IP = urlopen('http://instance-data/latest/meta-data/public-ipv4').read()
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ob3+i2$#v1gs9hiy%b@ub9!-pa&-nd0s1kf62t8s(c88m-acpd'

# SECURITY WARNING: don't run with debug turned on in production!
<<<<<<< HEAD
DEBUG = True
=======
DEBUG = False
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c

ALLOWED_HOSTS = [AWS_PUBLIC_IP]


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'NotifierApp'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'AwsNotifier.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AwsNotifier.wsgi.application'

<<<<<<< HEAD

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

=======
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


<<<<<<< HEAD
# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
=======
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


<<<<<<< HEAD
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
=======
>>>>>>> c3b3e3206355290b64bbd291f76241588ebdcd0c

STATIC_URL = '/static/'
STATIC_PATH = os.path.join(BASE_DIR,'static')



STATICFILES_DIRS = (
    STATIC_PATH,
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
